### ISSUE TITLE
elm port

### ISSUE THREAD

**Issue by bsouthga** [Swizec/react-fractals#3]
Not really an issue, but I tried an elm port if you wanted another framework for comparison: https://github.com/bsouthga/pythagoras-fractal

**Comment by Swizec** [comment]
Omg I've been wanting to explore Elm for *so long*. Thank you!

**Comment by bsouthga** [comment]
np! not sure if its the most idiomatic elm, as I'm learning to (specifically my use of tuples instead of records)
